ARG RELEASE
FROM debian:${RELEASE}
ARG RELEASE

RUN apt-get update -q \
    && apt-get install -qy --no-install-recommends \
    qemu-user-static \
    binfmt-support \
    debootstrap \
    xz-utils

RUN debootstrap --foreign --variant=minbase --no-check-gpg --arch=armhf ${RELEASE} armhf http://archive.raspbian.org/raspbian/

RUN mkdir output
RUN tar --numeric-owner -caf output/rootfs.tar.xz -C armhf --transform='s,^./,,' .
